[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cpp-gen"
version = "2.1.0"
description = "C++ boilerplate generator"
dependencies = ["Jinja2==3.1.6", "python-dotenv==1.2.3"]

[project.scripts]
cpp-gen = "cpp_gen.cli:main"

[tool.setuptools.package-data]
cpp_gen = ["templates/*.j2"]
